#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#$HOME/.config/polybar/launch.sh --colorblocks
~/.config/polybar/launch.sh
bash ~/.config/polybar/scripts/pywal.sh ~/Pictures/mx-shimmer-red-eyes-anime-girl-x0.jpg &
feh --bg-fill $HOME/Pictures/mx-shimmer-red-eyes-anime-girl-x0.jpg
picom --experimental-backends &
vmware-user  &
wmname LG3D &
xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 0
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
