#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#$HOME/.config/polybar/launch.sh --colorblocks
~/.config/polybar/launch.sh
bash ~/.config/polybar/scripts/pywal.sh ~/Pictures/mx-shimmer-red-eyes-anime-girl-x0.jpg &
feh --bg-fill $HOME/Pictures/mx-shimmer-red-eyes-anime-girl-x0.jpg
picom --experimental-backends &
vmware-user  &
wmname LG3D &
xsetroot -cursor_name left_ptr &

# Workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# Windows Config
bspc config border_width 0
bspc config focus_follows_pointer true
bspc config pointer_modifier shift
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Mice bindings
#   Shift + Left Click to move floating windows
bspc config pointer_action1 move

#   Shift + Right Click resizes the window by side
bspc config pointer_action3 resize_side

#   Shift + Right Click button resize by corner
bspc config pointer_action3 resize_corner


# Window Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Window State Configs
bspc rule -a GParted state=floating focus=on
bspc rule -a Lxappearance state=floating focus=on
bspc rule -a SimpleScreenRecorder state=floating focus=on
bspc rule -a NetworkManager state=floating focus=on
bspc rule -a Alacritty state=tiled focus=on
bspc rule -a speedcrunch state=floating focus=on
bspc rule -a Viewnior focus=on state=tiled
bspc rule -a Emacs state=tiled focus=on
