#!/bin/bash

PCOM="$HOME/.config/picom/picom.conf"
POLY="$HOME/.config/polybar/colorblocks/config.ini"

CON=$(grep 'corner-radius = 15' $PCOM)
#COFF=$(grep 'corner-radius = 0' $PCOM)
PON=$(grep -E 'radius-top = 15|radius-bottom = 15' $POLY)

function change_borders(){
    #"$@"
    #local status=$?
    if echo $CON $PON | grep -q -E 'corner-radius = 15|radius-top = 15|radius-bottom = 15'; then
        echo 'Changing the borders to sharp borders'
        sed -i -e "s/corner-radius = 15.0/corner-radius = 0.0/g" $PCOM
        sed -i -e "s/radius-top = 15/radius-top = 0/g" $POLY
        sed -i -e "s/radius-bottom = 15/radius-bottom = 0/g" $POLY
        sed -i -e "s/modules-left = sep right1 workspaces left1 sep right2 ethernet left2 sep right2 vpn left2 sep right2 target left2 sep right2 nm-launcher left2 sep/modules-left= sep workspaces sep ethernet sep vpn sep target sep nm-launcher/g" $POLY
        sed -i -e "s/modules-right = right2 cpu memory date left2 sep/modules-right = cpu memory date sep/g" $POLY
    else
        echo 'Changing the borders to rounded borders'
        sed -i -e "s/corner-radius = 0.0/corner-radius = 15.0/g" $PCOM
        sed -i -e "s/radius-top = 0/radius-top = 15/g" $POLY
        sed -i -e "s/radius-bottom = 0/radius-bottom = 15/g" $POLY
        sed -i -e "s/modules-left= sep workspaces sep ethernet sep vpn sep target sep nm-launcher/modules-left = sep right1 workspaces left1 sep right2 ethernet left2 sep right2 vpn left2 sep right2 target left2 sep right2 nm-launcher left2 sep/g" $POLY
        sed -i -e "s/modules-right = cpu memory date sep/modules-right = right2 cpu memory date left2 sep/g" $POLY
    fi

    #return $status
}

# Picom Configuration and Reload polybar
if ! pgrep -x "picom" > /dev/null
then
    picom --config ~/.config/picom/picom.conf &
fi

WALL=$(tail -n 1 ~/.fehbg | cut -d ' ' -f 4 | sed -e "s/^'//" -e "s/'$//")
bash ~/.config/polybar/colorblocks/scripts/pywal.sh $WALL

change_borders
