#!/bin/sh

WAL=$(ls ~/Pictures/*.* | shuf -n 1)
bash ~/.config/polybar/scripts/pywal.sh $WAL
# Avoid the script from killing the picom process
#if ! pgrep -x "picom" > /dev/null
#then
#    picom &
#fi

compton --config ~/.config/compton/compton.conf &
