#!/bin/sh

WAL=$(ls ~/Pictures/*.* | shuf -n 1)
bash ~/.config/polybar/colorblocks/scripts/pywal.sh $WAL

# Picom Configuration
if ! pgrep -x "picom" > /dev/null
then
    picom --config ~/.config/picom/picom.conf &
fi

# Compton Configuration
#compton --config ~/.config/compton/compton.conf &
