#!/bin/bash

ALACRITTY="$HOME/.config/alacritty/alacritty.yml"

if cat $ALACRITTY | grep -q 'size: 25.0'; then
    # Changing the alacritty font size to 15
    sed -i -e "s/size: 25.0/size: 15.0/g" $ALACRITTY
elif cat $ALACRITTY | grep -q 'size: 15.0'; then
    # Changing the alacritty font size to 25
    sed -i -e "s/size: 15.0/size: 25.0/g" $ALACRITTY
fi
